"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const db_1 = require("./db");
var serialized_query_1 = require("serialized-query");
exports.SerializedQuery = serialized_query_1.SerializedQuery;
exports.default = db_1.DB;
var db_2 = require("./db");
exports.DB = db_2.DB;
exports.FirebaseBoolean = db_2.FirebaseBoolean;
var abstracted_firebase_1 = require("abstracted-firebase");
exports.RealTimeDB = abstracted_firebase_1.RealTimeDB;
